#!/usr/bin/env bash
set -euo pipefail

required_vars=(
  DATABASE_URL
  SECRET_KEY
  ADMIN_EMAIL
  ADMIN_PASSWORD
)

missing=()
for name in "${required_vars[@]}"; do
  if [[ -z "${!name:-}" ]]; then
    missing+=("$name")
  fi
done

if (( ${#missing[@]} > 0 )); then
  printf 'Missing required Codex Cloud environment variables: %s\n' "${missing[*]}" >&2
  exit 1
fi

python3 -m pip install --user -r requirements.txt

cat > .env <<EOF
APP_ENV=${APP_ENV:-production}
APP_INSTANCE_ROLE=${APP_INSTANCE_ROLE:-primary}
SECRET_KEY=${SECRET_KEY}
DATABASE_URL=${DATABASE_URL}
ADMIN_EMAIL=${ADMIN_EMAIL}
ADMIN_PASSWORD=${ADMIN_PASSWORD}
AUTO_INIT_DB=${AUTO_INIT_DB:-false}

GOOGLE_ADS_ALLOW_MUTATIONS=${GOOGLE_ADS_ALLOW_MUTATIONS:-true}
GOOGLE_ADS_DRY_RUN=${GOOGLE_ADS_DRY_RUN:-false}
GOOGLE_ADS_OPTIMIZATION_DATE_RANGE=${GOOGLE_ADS_OPTIMIZATION_DATE_RANGE:-LAST_7_DAYS}
GOOGLE_ADS_BASELINE_DATE_RANGE=${GOOGLE_ADS_BASELINE_DATE_RANGE:-LAST_30_DAYS}
GOOGLE_ADS_CHANGE_COOLDOWN_HOURS=${GOOGLE_ADS_CHANGE_COOLDOWN_HOURS:-24}
GOOGLE_ADS_MIN_CONVERSIONS_FOR_BID_CHANGE=${GOOGLE_ADS_MIN_CONVERSIONS_FOR_BID_CHANGE:-5}
GOOGLE_ADS_MIN_COST_FOR_ACTION=${GOOGLE_ADS_MIN_COST_FOR_ACTION:-25}
GOOGLE_ADS_ZERO_CONVERSION_MIN_CLICKS=${GOOGLE_ADS_ZERO_CONVERSION_MIN_CLICKS:-10}
GOOGLE_ADS_MAX_BUDGET_CHANGE_PCT=${GOOGLE_ADS_MAX_BUDGET_CHANGE_PCT:-0.20}
GOOGLE_ADS_MAX_TARGET_ROAS_CHANGE_PCT=${GOOGLE_ADS_MAX_TARGET_ROAS_CHANGE_PCT:-0.10}
GOOGLE_ADS_MIN_DAILY_BUDGET=${GOOGLE_ADS_MIN_DAILY_BUDGET:-1}
GOOGLE_ADS_ALLOW_TOTAL_BUDGET_INCREASE=${GOOGLE_ADS_ALLOW_TOTAL_BUDGET_INCREASE:-false}
EOF

python3 scripts/init_app_db.py

printf 'Cloud environment prepared. Google OAuth tokens are expected from Postgres, not local env files.\n'
